# -*- conf -*-

include=~/.config/foot/colors.ini

locked-title=no
font=Iosevka:size=11, Iosevka:size=11, Code2000:size=11
font-bold=Iosevka:style=bold:size=11, Iosevka:style=bold:size=11, Code2000:size=11
font-italic=Iosevka:style=italic:size=11, Iosevka:style=italic:size=11, Code2000:size=11
font-bold-italic=Iosevka:style=bold italic:size=11, Iosevka:style=bold italic:size=11, Code2000:size=11

pad=6x6 center-when-maximized-and-fullscreen

[scrollback]
lines=9999
indicator-position=relative

[cursor]
style=block
blink=no

[mouse]
hide-when-typing=yes

[tweak]
grapheme-shaping=yes
overflowing-glyphs=yes

[key-bindings]
scrollback-up-page=none
scrollback-up-half-page=none
scrollback-up-line=none
scrollback-down-page=none
scrollback-down-half-page=none
scrollback-down-line=none
scrollback-home=none
scrollback-end=none
search-start=none
spawn-terminal=none
show-urls-launch=Control+Shift+o
unicode-input=none
show-urls-copy=Control+Shift+u
show-urls-persistent=none
prompt-prev=none
prompt-next=none

[url]
launch=firefox --new-window ${url}

[csd]
preferred=none

# vim: ft=dosini
