.pragma library

var rows = [
  [
    {id: "ESC", label: "ESC", width: 1},
    {id: "F1", label: "F1", width: 1},
    {id: "F2", label: "F2", width: 1},
    {id: "F3", label: "F3", width: 1},
    {id: "F4", label: "F4", width: 1},
    {id: "F5", label: "F5", width: 1},
    {id: "F6", label: "F6", width: 1},
    {id: "F7", label: "F7", width: 1},
    {id: "F8", label: "F8", width: 1},
    {id: "F9", label: "F9", width: 1},
    {id: "F10", label: "F10", width: 1},
    {id: "F11", label: "F11", width: 1},
    {id: "F12", label: "F12", width: 1},
    {id: "PRINT", label: "PRT", width: 1},
    {id: "INSERT", label: "INS", width: 1},
    {id: "DELETE", label: "DEL", width: 1}
  ],
  [
    {id: "GRAVE", label: "~", width: 1},
    {id: "1", label: "1", width: 1},
    {id: "2", label: "2", width: 1},
    {id: "3", label: "3", width: 1},
    {id: "4", label: "4", width: 1},
    {id: "5", label: "5", width: 1},
    {id: "6", label: "6", width: 1},
    {id: "7", label: "7", width: 1},
    {id: "8", label: "8", width: 1},
    {id: "9", label: "9", width: 1},
    {id: "0", label: "0", width: 1},
    {id: "MINUS", label: "-", width: 1},
    {id: "EQUAL", label: "=", width: 1},
    {id: "BACKSPACE", label: "BACKSPACE", width: 2},
    {id: "HOME", label: "HOME", width: 1},
    {id: "END", label: "END", width: 1},
    {id: "PAGEUP", label: "PGUP", width: 1}
  ],
  [
    {id: "TAB", label: "TAB", width: 1.5},
    {id: "Q", label: "Q", width: 1},
    {id: "W", label: "W", width: 1},
    {id: "E", label: "E", width: 1},
    {id: "R", label: "R", width: 1},
    {id: "T", label: "T", width: 1},
    {id: "Y", label: "Y", width: 1},
    {id: "U", label: "U", width: 1},
    {id: "I", label: "I", width: 1},
    {id: "O", label: "O", width: 1},
    {id: "P", label: "P", width: 1},
    {id: "BRACKETLEFT", label: "[", width: 1},
    {id: "BRACKETRIGHT", label: "]", width: 1},
    {id: "BACKSLASH", label: "\\", width: 1.5},
    {id: "PAGEDOWN", label: "PGDN", width: 1}
  ],
  [
    {id: "CAPSLOCK", label: "CAPS", width: 1.8},
    {id: "A", label: "A", width: 1},
    {id: "S", label: "S", width: 1},
    {id: "D", label: "D", width: 1},
    {id: "F", label: "F", width: 1},
    {id: "G", label: "G", width: 1},
    {id: "H", label: "H", width: 1},
    {id: "J", label: "J", width: 1},
    {id: "K", label: "K", width: 1},
    {id: "L", label: "L", width: 1},
    {id: "SEMICOLON", label: ";", width: 1},
    {id: "APOSTROPHE", label: "'", width: 1},
    {id: "ENTER", label: "ENTER", width: 2.2}
  ],
  [
    {id: "SHIFT", label: "SHIFT", width: 2.3},
    {id: "Z", label: "Z", width: 1},
    {id: "X", label: "X", width: 1},
    {id: "C", label: "C", width: 1},
    {id: "V", label: "V", width: 1},
    {id: "B", label: "B", width: 1},
    {id: "N", label: "N", width: 1},
    {id: "M", label: "M", width: 1},
    {id: "COMMA", label: ",", width: 1},
    {id: "PERIOD", label: ".", width: 1},
    {id: "SLASH", label: "/", width: 1},
    {id: "SHIFT_R", label: "SHIFT", width: 2.7}
  ],
  [
    {id: "CTRL", label: "CTRL", width: 1.4},
    {id: "SUPER", label: "SUPER", width: 1.4},
    {id: "ALT", label: "ALT", width: 1.4},
    {id: "SPACE", label: "SPACE", width: 6.4},
    {id: "ALT_R", label: "ALT", width: 1.4},
    {id: "SUPER_R", label: "SUPER", width: 1.4},
    {id: "LEFT", label: "◀", width: 1},
    {id: "DOWN", label: "▼", width: 1},
    {id: "UP", label: "▲", width: 1},
    {id: "RIGHT", label: "▶", width: 1}
  ]
]
