terminal = "kitty"
terminal_dropdown = "kitty --hold --session /home/julien/.config/kitty/sessions/dropdown.conf"
terminal_editor = "kitty nvim"
gui_editor = "emacs" 
calcurse = "kitty --session /home/julien/.config/kitty/sessions/calcurse.conf"
ranger = "kitty --session /home/julien/.config/kitty/sessions/ranger.conf"
pacseek = "kitty --session /home/julien/.config/kitty/sessions/pacseek.conf"
note_editor = "kitty --session /home/julien/.config/kitty/sessions/note_editor.conf"
web_browser = "firefox"
app_launcher = "rofi -show run"
sidebar_app_launcher = "rofi -show drun -config /home/julien/.config/rofi/sidebar.rasi"
power_menu = "sh /home/julien/.config/rofi/scripts/power-menu.sh"
screenshot_menu = "sh /home/julien/.config/rofi/scripts/screenshot-menu.sh"
display_power_menu = "sh /home/julien/.config/rofi/scripts/display-power-menu.sh"
change_theme_random = "sh /home/julien/.config/myscripts/qtile-pywal.sh" 
file_manager_gui = "pcmanfm"
emacs = "emacsclient -c -a emacs"
btop = "kitty btop"


