general {
    lock_cmd = notify-send -a "Hyprland" "Locking..."
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = ~/.config/hypr/scripts/wake-gate.py
}

listener {
    timeout = 900
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

listener {
    timeout = 1800
    on-timeout = systemctl suspend
}
