general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = hyprctl dispatch dpms on && sleep 1 && loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
    inhibit_sleep = 3
    ignore_dbus_inhibit = false
}

listener {
    timeout = 900
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

listener {
    timeout = 3600
    on-timeout = ~/.dotfiles/rust-tools/target/release/hypridle-suspend
}
