Net/ThemeName "PiXflat"
Net/IconThemeName "PiXflat"
Net/EnableEventSounds 1
Net/EnableInputFeedbackSounds 1
Gtk/FontName "PibotoLt 12"
Gtk/ToolbarStyle 3
Gtk/ButtonImages 0
Gtk/MenuImages 0
Gtk/CursorThemeSize 24
Gtk/AutoMnemonics 1
Gtk/EnableMnemonics 1
Gtk/ColorScheme "fg_color:#FFB0C6\nbg_color:#050309\nbase_color:#07050B\ntext_color:#FFB0C6\nselected_bg_color:#965889\nselected_fg_color:#F5C8D3\ntooltip_bg_color:#B36478\ntooltip_fg_color:#FFB0C6\nbar_bg_color:#050309\nbar_fg_color:#FFB0C6\n"
Gtk/CursorThemeName "PiXflat"
Gtk/ToolbarIconSize 3
Gtk/IconSizes "gtk-large-toolbar=24,24"
Xft/Antialias 1
Xft/Hinting 1
Xft/HintStyle "hintfull"
Xft/RGBA "rgb"
