# Foreground / background
foreground #EAF2FF
background #0B1020
selection_foreground #0B1020
selection_background #32FF7E

# Cursor
cursor #EAF2FF
cursor_text_color #0B1020

# URL color
url_color #FFFFFF 

# Tabs
active_tab_background   #32FF7E
active_tab_foreground   #0B1020
inactive_tab_background #111827
inactive_tab_foreground #EAF2FF
tab_bar_background      #0B1020
# Window separator
window_border_width 1px

# Standard 16-color palette
color0  #0B1020
color8  #556070

color1  #FF3B5C
color9  #FF6680

color2  #32FF7E
color10 #76FFAA

color3  #FFE95C
color11 #FFF08A

color4  #6C8CFF
color12 #91A8FF

color5  #FF4FD8
color13 #FF83E6

color6  #26F5FF
color14 #78FAFF

color7  #EAF2FF
color15 #FFFFFF
