# Foreground / background
foreground {{foreground}}
background {{background}}
selection_foreground {{color15}}
selection_background {{color2}}

# Cursor
cursor {{foreground}}
cursor_text_color {{color15}}

# URL color
url_color {{color15}} 

# Tabs
active_tab_background   {{color2}}
active_tab_foreground   {{color15}}
inactive_tab_background {{color0}}
inactive_tab_foreground {{foreground}}
tab_bar_background      {{background}}
# Window separator
window_border_width 1px

# Standard 16-color palette
color0  {{background}}
color8  {{color8}}

color1  {{color1}}
color9  {{color9}}

color2  {{color2}}
color10 {{color10}}

color3  {{color3}}
color11 {{color11}}

color4  {{color4}}
color12 {{color12}}

color5  {{color5}}
color13 {{color13}}

color6  {{color6}}
color14 {{color14}}

color7  {{color7}}
color15 {{color15}}
